// @generated by kysely-codegen, do not edit manually
// Run `npm run db:types` to regenerate
import type { Generated, Insertable, Selectable, Updateable } from 'kysely'

export interface UsersTable {
  id: Generated<number>
  email: string
  username: string
  password: string
  inviter_code: number | null
  created_at: number
  updated_at: number
  deleted_at: Generated<number>
  is_deleted: Generated<number>
  version: Generated<number>
}

export interface DB {
  users: UsersTable
}

export type User = Selectable<UsersTable>
export type NewUser = Insertable<UsersTable>
export type UserUpdate = Updateable<UsersTable>
